import { Job } from './types';

export const jobOffers: Job[] = [
  {
    "id": 1,
    "status": "Active",
    "company": "Wirinix",
    "account": "Appointment Setter (Roofing & Solar)",
    "shifts": "5:00 PM to 2:00 AM, 5 days/week with 2 fixed days off",
    "interview": "Not specified",
    "location": "Work from Home",
    "graduation": "Not specified",
    "nationality": "Not specified",
    "maxAge": null,
    "language": "B2–C1 English Level",
    "languageRequirement": "B2",
    "salary": "15,000 EGP net + 2,000 EGP KPIs + bonus per appointment above target",
    "process": "Voice recording / Interview via WhatsApp",
    "training": "5 days (paid after passing probation)",
    "details": "We are currently hiring for Appointment Setter (Work from Home) positions for two accounts: Roofing & Solar\n\nRequirements:\nEnglish level B2–C1\nCold calling and sales experience\n\nOffer Details:\nNet Salary: 15,000 EGP\nKPIs : 2,000 EGP\nShift: 5:00PM - 2:00 AM\nWorking Days: 5 days/week with 2 fixed days off\nTraining: 5 days (paid if you pass the probation period)\nBonus: For each appointment above the target\n\nEquipment Requirements: Stable internet connection, headset, and PC or laptop",
    "locationType": "remote",
    "targetLanguage": "english"
  },
  {
    "id": 2,
    "status": "Active",
    "company": "Launch Pad",
    "account": "Sales Agent (Hotel Packages)",
    "shifts": "3:30 PM to 12:30 AM, Monday–Friday",
    "interview": "Not specified",
    "location": "Not specified (assumed office)",
    "graduation": "Bachelor's degree or equivalent preferred",
    "nationality": "Not specified",
    "maxAge": 30,
    "language": "C1 English Level",
    "languageRequirement": "C1",
    "salary": "12,000 EGP net + commissions up to 10,000 EGP",
    "process": "Not specified",
    "training": "Provided",
    "details": "Job Title: Sales Agent\nAs a Sales Agent at Launch Pad Travel, your primary responsibility is to engage with potential customers through phone calls to promote and sell tailored hotel packages. You will connect with clients abroad, introduce them to our exclusive offers, and ensure a smooth booking process while delivering exceptional service.\n\nJob Responsibilities\nOutbound Calling: Make a high volume of outbound calls daily to potential customers, primarily foreign clients, introducing them to our hotel packages and travel services.\nPresent Offers Effectively: Clearly communicate the features, benefits, and pricing of our hotel packages, tailoring the conversation to meet each customer's specific travel needs.\nHandle Inquiries: Address questions or concerns raised by potential clients during calls, providing accurate and timely information.\nFollow Up on Leads: Pursue leads generated through marketing campaigns or previous inquiries to maximize conversion rates.\nClose Sales: Persuasively guide potential customers to make bookings, meeting or exceeding sales targets.\nUpdate Customer Records: Accurately log call outcomes, customer details, and booking information in the company database.\nMaintain Professionalism: Build rapport with international clients, always ensuring polite and professional communication.\nCollaborate with the Team: Work closely with colleagues to refine sales techniques and share insights for improving customer engagement.\n\nEducation\nBachelor's degree or equivalent experience in Sales is preferred.\nPrevious experience in tele-sales or call center roles is a plus.\n\nSkills and Qualifications\nAge: Maximum 30 years old.\nEnglish Proficiency: C1 level, with a strong ability to communicate clearly with foreign clients.\nExcellent verbal communication and persuasive skills.\nProficiency in using productivity tools (Microsoft Excel, Google Sheets).\nAbility to handle high-pressure situations and meet targets.\n\nCompensation and Benefits\nNet Salary: 12,000 EGP.\nCommissions: Up to 10,000 EGP.\nTraining is provided to enhance sales and communication skills.\nOpportunities for career advancement within the company.\n\nWorking Conditions\nWorking Days: Monday to Friday. / Weekends: Saturday and Sunday off.\nWorking Hours: 3:30 PM to 12:30 AM. / Holidays: Observing American federal holidays and both Eids.",
    "locationType": "office",
    "targetLanguage": "english"
  },
  {
    "id": 3,
    "status": "Active",
    "company": "Aces",
    "account": "Part Time Telesales Agent",
    "shifts": "Part time: 2 days/week + 3 days in second week (specific hours not given)",
    "interview": "Not specified",
    "location": "Abbasiya | Syndicate Of Applicators",
    "graduation": "No Experience Needed",
    "nationality": "Egyptians only",
    "maxAge": null,
    "language": "Fluent English",
    "languageRequirement": "C1",
    "salary": "7,000 EGP basic net + uncapped commission",
    "process": "Not specified",
    "training": "Paid training once hired",
    "details": "ACEs contact center is Now hiring part time Telesales agents!\n\nJoin our team , start training next week, Grow fast and let’s succeed together\n\nSalary: 7K basic net + Uncapped Commission\nWorking Hours: Part Time 2 days a week + 3 days in the second week\nLocation: Abbasiya | Syndicate Of Applicators\n\nRequirements:\nFluent in English\nNo Experience Needed\nEgyptians only\n\nBenefits:\nChance to get Promoted in 6 months\nPaid training once hired\nTransportation\nFriendly work Environment\nSocial insurance\nMedical insurance and profit share after 1 year",
    "locationType": "office",
    "targetLanguage": "english"
  },
  {
    "id": 4,
    "status": "Active",
    "company": "TTC",
    "account": "Telesales Agent (US Accounts)",
    "shifts": "3 PM to 11 PM (fixed), Saturday & Sunday off",
    "interview": "Voice recording introducing yourself in English via WhatsApp",
    "location": "Makram Ebid, Nasr City",
    "graduation": "Graduates, undergrads, gap year, dropouts welcomed",
    "nationality": "Egyptian Only",
    "maxAge": 28,
    "language": "Excellent to Fluent English (B2+/C1)",
    "languageRequirement": "B2",
    "salary": "12,000 EGP net + unlimited commissions + KPIs",
    "process": "Send voice record via WhatsApp",
    "training": "Paid testing period",
    "details": "TTC is looking for Telesales Agents to join our US Accounts 🇺🇸.\n\n*What you will get:*\n▪️ Net 12000 EGP + Unlimited Commissions + KPIs 💸\n▪️ Paid testing period and bonus if you pass it 🎉\n▪️ Monthly & Quarterly & Yearly Bonuses 💰\n▪️ Transportation Provided (The Back-Way) 🚌\n▪️ Optional benefits packages\n▪️ Friendly and collaborative team environment. 🤝\n\n*Working Condition:*\n▪️ 3 PM till 11 PM (including 1 hour as a break).\n▪️ Fixed Shift (7 Working Hours Only).\n▪️ 2 Days Off Fixed (Saturday & Sunday)\n▪️ Location: Makram Ebid, Nasr City\n\n*Requirements:*\n▪️ Excellent to Fluent English (B2+/C1 level) is a must 🚫\n▪️ No Experience Needed.\n▪️ Graduates, Undergrads, Gap year, dropout are welcomed 🧑‍🎓\n▪️ age: 18 - 28 YO.\n▪️ Egyptian Only.\n\nReady to Apply?\nPlease send a record introducing yourself in English via WA",
    "locationType": "office",
    "targetLanguage": "english"
  },
  {
    "id": 5,
    "status": "Active",
    "company": "TTP",
    "account": "Telesales Agent",
    "shifts": "3:00 PM - 12 AM, weekends Saturday & Sunday",
    "interview": "Not specified",
    "location": "Not specified (transportation drop off points: Masr El Gdeda, Nasr City)",
    "graduation": "Grads and UG can apply",
    "nationality": "Not specified",
    "maxAge": null,
    "language": "B2+ English level",
    "languageRequirement": "B2",
    "salary": "15,000 EGP net + commission up to 9K",
    "process": "Not specified",
    "training": "Not specified",
    "details": "Position: Telesales Agent\n\nB2+ English level is required\nGrads and UG can apply\n\nSalary: 15,000 L.E Net + Commission up to 9K\n\nWorking hours: 3:00 PM - 12 AM\nWeekends: Saturday & Sunday\n\nTransportation: On the way back home only.\nDrop off Points: Masr El Gdeda and Nasr City\nDrop off points for guys & door to door for girls",
    "locationType": "office",
    "targetLanguage": "english"
  },
  {
    "id": 6,
    "status": "Active",
    "company": "REZ",
    "account": "Real Estate Cold-caller",
    "shifts": "Full-time 9-hour shift (8 hours work + 1 hour break), Monday–Friday, Saturday & Sunday off",
    "interview": "Not specified",
    "location": "Work from Home",
    "graduation": "Not specified",
    "nationality": "Not specified",
    "maxAge": null,
    "language": "B2/C1 English level",
    "languageRequirement": "B2",
    "salary": "$250 basic + $100 KPIs + $100 bonus per 20 leads above target",
    "process": "Not specified",
    "training": "Not specified",
    "details": "Real Estate Cold-caller\nWFH\n\nPayment:\nBasic salary: 250$\nKPIS: 100$\nBonus: 100$ for every 20 leads above the target.\n\nRequirements:\nB2/C1 English level\nExperience in cold calling real estate is a MUST\n\nWorking conditions:\nFull-time 9-hour shift (8 hours required and 1 hour as a break)\nPaid American holidays.\nSaturday and Sunday are fixed off-days (Work days Monday to Friday)",
    "locationType": "remote",
    "targetLanguage": "english"
  },
  {
    "id": 7,
    "status": "Active",
    "company": "Assets",
    "account": "Appointment Setter (Life Coaching Campaign)",
    "shifts": "6 days/week, 8 hours/day within 4pm to 5am",
    "interview": "Not specified",
    "location": "Awel Makram",
    "graduation": "No exp needed",
    "nationality": "Egyptians only",
    "maxAge": null,
    "language": "English B2+ - C2, handle 30 min calls",
    "languageRequirement": "B2",
    "salary": "15,000 EGP basic + commission up to 6k/month + weekly bonuses + 2k transportation allowance for ladies",
    "process": "Not specified",
    "training": "Not specified",
    "details": "Appointment setter new niche (life coaching campaign) 🚨\n\n*Recuirments*\nEgyptians only\nNo exp needed\nEnglish B2+ - C2\nSomeone can handle a 30 m calls\n\nBenefits 💸\nBasic salary 15k\nCommission are weekly and daily up to 6k a month\nWeekly bonuses on sales strating from 35$ up to 125$\n\n2k transportation allowance for *ladies* 💁🏻‍♀️\n\n6 days a week, 8hours a day ⏰\n(within 4pm to 5am)\n\n*Location*\nAwel Makram",
    "locationType": "office",
    "targetLanguage": "english"
  },
  {
    "id": 8,
    "status": "Active",
    "company": "BIS",
    "account": "Telesales (USA Campaign)",
    "shifts": "3:00 to 11:00 PM, Monday–Friday, Saturday & Sunday off",
    "interview": "Not specified",
    "location": "Makram Ebeid, Nasr Road - Nasr City",
    "graduation": "Graduates & Undergraduates",
    "nationality": "Not specified",
    "maxAge": null,
    "language": "Fluent/Excellent English",
    "languageRequirement": "C1",
    "salary": "10,000 EGP basic + commissions up to 20K",
    "process": "Not specified",
    "training": "5 days (paid)",
    "details": "We are HIRING Fluent/Excellent English Speakers!\nCNS Marketing Solutions is looking for Fluent/Excellent English Speakers for Telesales Vacancy in USA Campaign🇺🇸\nRequirements:\nFluent/Excellent command of English .\nNon-experience is needed.\nGraduates & Undergraduates are welcome to apply.\nWorking days: Monday - Friday\nSaturdays and Sundays are OFF\n3:00 till 11:00 PM 1 Hour break Included.\n(Fixed shifts)\n5 Days Training (Paid).\n📍Makram Ebeid, Nasr Road - Nasr City\n\nSalary: 10K Basic salary + Commissions UP to 20K 💸💸\n🚫No transportations\n🚫No WFH\n🚫 No part time",
    "locationType": "office",
    "targetLanguage": "english"
  },
  {
    "id": 9,
    "status": "Active",
    "company": "Cataleads",
    "account": "Real Estate Appointment Setter (Inside Sales Agent)",
    "shifts": "Between 5pm and 2am (fixed, including 1 hour break), Saturday & Sunday off",
    "interview": "Not specified",
    "location": "Nasr City, Cairo",
    "graduation": "Graduates, drop outs, students, gap years",
    "nationality": "Foreigners welcome",
    "maxAge": 30,
    "language": "Fluent English (C1/C2)",
    "languageRequirement": "C1",
    "salary": "$3.5/hr ~ $5/hr via Payoneer + uncapped bonus (average 40K to 60K EGP)",
    "process": "Not specified",
    "training": "Fully paid training (3–4 business days)",
    "details": "📢 Real Estate Appointment setting- CataLeads Systems\n*Position:* Inside Sales Agent (ISA)- Appointment setter\n*Work Model:* On-site – Nasr City, Cairo\n– Fixed weekend off (Saturday & Sunday)\n-Working hours are between 5pm and 2am fixed- Including one hour break.\n*🔹Requirements:*\n– Fluent English (C1/ C2 English level – spoken & written)\n– Previous *direct telesales experience* is a must (cold calling only, 6 months minimum)\n– Real estate background is a plus\n– Foreigners are welcome to apply\n-Graduates, drop outs, students, and gap years\n-Max Age is 30 Years Old.\n*💰Offer & Benefits :*\n*Average potential earning anywhere from 40K EGP to 60K EGP*\n\n– $3.5/hr ~$5/hr based on performance via *Payoneer* (USD)\n–uncapped bonus, the more appointments you book the more money you make.\n-Any Appointment between 30~39 appointments, you get $5 each.\nIf you got 40+ appointments, you'd get paid $8 per appointment.\nEx: 45 appointments bonus= (45-30) $8= 15 *$8=$120\n\nTop achievers' Potential earning is $1000~$1200+\n\n– *Fully paid training* (3–4 business days)\n*Transportation Provided.*\nDoor to door for Females “Ride back home.\n3000 EGP Transportation Allowance for males.\n\nAccess to annual balance after 3 months.",
    "locationType": "office",
    "targetLanguage": "english"
  },
  {
    "id": 10,
    "status": "Active",
    "company": "Creative Basket",
    "account": "Tele Sales / Travel Advisor",
    "shifts": "4 PM to 1 AM (including 1 hour break), Saturday & Sunday off",
    "interview": "Not specified",
    "location": "HO – Nasr City",
    "graduation": "Fresh & Experienced",
    "nationality": "Not specified",
    "maxAge": null,
    "language": "B2+ – C1 English",
    "languageRequirement": "B2",
    "salary": "$250 – $400 including KPI + target commission",
    "process": "Not specified",
    "training": "Not specified",
    "details": "#Creative Basket Position:* Tele Sales / Travel Advisor\nLocation: HO – Nasr City\nType: Full-time\nNumber of openings: 3 - 6 / Candidate\nshift Timing: from 4 PM To 1 AM (included 1 H break)\nDays Off: Saturday & Sunday\nSalary: 250$ – 400$ including KPI (Contingent Upon Experience) + target commission\nEnglish level: B2+ – C1 is a must\nRequirements:\n-Experience level: Fresh & Experienced.\n-Housing / Travel Experience is Preferable.\n-Tele Sales Experience is a must.",
    "locationType": "office",
    "targetLanguage": "english"
  },
  {
    "id": 11,
    "status": "Active",
    "company": "Nexaura",
    "account": "Cold-Calling Agent",
    "shifts": "4:00 PM – 12:00 AM",
    "interview": "Not specified",
    "location": "Not specified (assumed office)",
    "graduation": "Not specified",
    "nationality": "Not specified",
    "maxAge": null,
    "language": "Fluent English",
    "languageRequirement": "C1",
    "salary": "Commission-based: 1,000 EGP per completed deal (typical 10–25 deals or more)",
    "process": "Not specified",
    "training": "5 days probation (less if experienced)",
    "details": "Nexaura Services is Hiring: Fluent English Cold-Calling Agents 🚨\n\n📞 Position: Cold-Calling Agent\n🕐 Working Hours: 4:00 PM – 12:00 AM\n\n💰 Compensation: Commission-Based\n• 1,000 EGP for every completed deal\n• Based on real performance numbers, agents typically close 10–25 deals or more\n\n📆 Probation Period: 5 Days (Less if you have experience)",
    "locationType": "office",
    "targetLanguage": "english"
  },
  {
    "id": 12,
    "status": "Active",
    "company": "Leadbull",
    "account": "Canadian Telesales Account",
    "shifts": "4 PM – 1 AM",
    "interview": "Send voice recording introducing yourself",
    "location": "Zahraa El Maadi (work from site, then WFH after 3 months)",
    "graduation": "Not specified",
    "nationality": "Not specified",
    "maxAge": null,
    "language": "B2+ English Level",
    "languageRequirement": "B2",
    "salary": "15,000 EGP basic + 5,000 EGP KPIs + daily spiffs + quarterly incentives + annual profit share",
    "process": "Voice recording via DM",
    "training": "Not specified",
    "details": "LeadBull is HIRING! 🔥🔥\nCanadian Tele sales Account\n\nPackage:\n💰 EGP 15K EGP Basic Salary\n🎯 EGP 5K KPIs\n💸 Daily spiffs\n💸 Quarterly incentives\n💸Annual profit share\n\nWho We’re Looking For:\n🗣️ B2+ English Level\n\nJob Details:\n🕓 Shift: 4 PM – 1 AM\n\n📍 Company Location: Zahraa El Maadi\n(Work from site)\n\n🌟 Availability to work from home after 3 months 🏠\n\nSend a DM with a Voice recording introducing yourself to APPLY.",
    "locationType": "office",
    "targetLanguage": "english"
  },
  {
    "id": 13,
    "status": "Active",
    "company": "Synergistic",
    "account": "Telesales Agent (Paid Internship)",
    "shifts": "2:00 AM to 10:00 AM (overnight fixed)",
    "interview": "Not specified",
    "location": "Nasr City, Cairo",
    "graduation": "No prior experience preferred",
    "nationality": "Non-Egyptians welcome, African nationalities not preferred except Sudanese",
    "maxAge": 25,
    "language": "Fluent English",
    "languageRequirement": "C1",
    "salary": "16,000 EGP per month + commission (90-day internship)",
    "process": "Not specified",
    "training": "Not specified",
    "details": "Position: Telesales Agent (Paid Internship – 90 Days)\n\nSalary: EGP 16,000 per month + commission\n\nInternship Duration: 90 days\n\nWorking Hours:\nShift: Overnight (fixed)\nTiming: 2:00 AM to 10:00 AM\nLocation: Nasr City, Cairo\n\nPreferred Age Group: 18 – 25 years old (younger candidates preferred)\n\nNationality:\nNon-Egyptians are welcome to apply\nNote: African nationalities are not preferred, except for Sudanese applicants who are welcome\n\nEnglish Proficiency:\nFluent English is required\nCandidates must be able to speak and understand English easily\n\nPlease prioritize candidates without prior experience, as they tend to be more adaptable and can absorb new information more easily. Keep this in mind when shortlisting for the role.",
    "locationType": "office",
    "targetLanguage": "english"
  },
  {
    "id": 14,
    "status": "Active",
    "company": "Symbios",
    "account": "Business Development Representative (BDR)",
    "shifts": "11:45 PM to 8:00 AM, Sunday night to Thursday night (Friday off)",
    "interview": "Not specified",
    "location": "Nasr City",
    "graduation": "Grads Only",
    "nationality": "Not specified",
    "maxAge": null,
    "language": "Fluent English (experienced cold caller)",
    "languageRequirement": "C1",
    "salary": "Up to 16,500 EGP net + uncapped commissions in USD + social & medical insurance",
    "process": "Not specified",
    "training": "Not specified",
    "details": "💰 Ready to Earn in USD?\n\nSymbios is Hiring – BDR - Business Development Representative\n\nIf you're an experienced cold caller who can:\n\n✔ Open doors\n✔ Handle objections\n✔ Book quality appointments\n\nThen we want YOU.\n\n🔥 Net Salary Up To 16.5K EGP\n🔥 Commissions in USD\n🔥 UNCAPPED Commission Structure\n🔥 Social & Medical Insurance\n🔥 Grads Only\n\nHigh performers only.\n\nNo cap. No limits. Just results.\n\nWorking Hours\n11:45 PM to 8:00 AM\n\nFrom Sunday Night (Monday) to Thursday Night (Friday)\n\nLocation 📍\nNasr City",
    "locationType": "office",
    "targetLanguage": "english"
  },
  {
    "id": 15,
    "status": "Active",
    "company": "Outsourcing 4 u (O4u)",
    "account": "Social Media Specialist (UK account)",
    "shifts": "Monday–Friday, 12pm–8:15pm (Ramadan 11am–5pm)",
    "interview": "Send voice note introducing yourself in English",
    "location": "Maadi",
    "graduation": "Not specified",
    "nationality": "Not specified",
    "maxAge": null,
    "language": "English B2 or above",
    "languageRequirement": "B2",
    "salary": "7,500 EGP net + negotiable raise every 3–6 months",
    "process": "Voice note via WhatsApp",
    "training": "Not specified",
    "details": " Social Media Specialist's requirements: -\nOutsourcing 4 you is looking for Social Media Specialist.\n📅 Book your interview today and start training 😉\nUK account\n• Monday - Friday, 12pm - 8:15pm\n• Ramadan timing 11 am - 5pm\n• English level is B2 or above.\n• Experience: 3 - 12 months.\n• Can use illustrator & Photoshop.\n• Salary 7.5k net + negotiable raise every 3 to 6 months.\n• Location: Maadi.\n* If you're interested, kindly send us a voice note introducing yourself in English.",
    "locationType": "office",
    "targetLanguage": "english"
  }
]